### ISSUE TITLE
Lamps won't turn on

### ISSUE THREAD

**Issue by madeinholland** [leonvandenbeukel/3D-7-Segment-Digital-Clock#19]
I have gone to upload the firmware with the liberals tho the nano.
But when I am connected to de Bluetooth HC-05 and in the app, the lamp doesn't work.

my wiring is good it has voltage over eas lamp (+5v).  The only thing is it won't light up any of the lamps I think it lays in the android app. because I didn't make any changes in the liberals and your document. 

the Din and ground do not have voltage over them. Besides that, the lamps can be turned on when I put voltage over them.
P.S I did not yet power it from the adaptor but with my pc.

Leon, can you help me tho finish your product?

**Comment by Alex-Ender35** [comment]
> Я пошел заливать прошивку с либералами на нано. Но когда я подключен к de Bluetooth HC-05 и в приложении, лампа не работает.
> 
> моя проводка в порядке, на лампе eas есть напряжение (+5В). Единственное, он не загорается ни одной из ламп, которые, я думаю, лежат в приложении для Android. потому что я не вносил никаких изменений в либералы и ваш документ.
> 
> Дин и земля не имеют на себе напряжения. Кроме того, лампы могут включаться, когда я подаю на них напряжение. PS Я его еще не запитывал от адаптера, а от своего пк.
> 
> Леон, не могли бы вы помочь мне закончить ваш продукт?

Hello. Have you been able to solve the problem with the lamps not working? If so, how?
