### ISSUE TITLE
Release STL on Thingiverse

### ISSUE THREAD

**Issue by fleaz** [leonvandenbeukel/3D-7-Segment-Digital-Clock#4]
Hi,

first of all: Thanks for this nice project. Will start to print it myself as soon as I have restocked my PLA ^^

My suggestion would be to publish the STL files on Thingiverse. This way a lot more people would see this cool project and can also share pictures of their prints and start to remix the files or help each other in the comments section. 

In my opinion this is a better platform for 3D Objects than GitHub.

Best regards,
Felix

**Comment by leonvandenbeukel** [comment]
Hi, sorry for the late response. The STL files are also on thingiverse: https://www.thingiverse.com/thing:2871608
