### ISSUE TITLE
problem with LED

### ISSUE THREAD

**Issue by icepol001** [leonvandenbeukel/3D-7-Segment-Digital-Clock#8]
I made your clock but I have a problem with LEDs.
places that should not shine are glowing white. can you help me ? thank you

**Comment by Milius605** [comment]
I have same problem. Pls help :-D

**Comment by leonvandenbeukel** [comment]
Please check the .ino file on line 59:

CRGB colorOFF  = CRGB(20,20,20);      // Color of the segments that are 'disabled'. You can also set it to CRGB::Black

Change "CRGB(20,20,20)" to CRGB::Black if you don't want a glowing white.

**Comment by Milius605** [comment]
It works! Thank you very much for your help and quick response
